language: node_js
node_js:
- node
before_script:
- npm install -g gulp-cli
script: gulp
deploy:
  provider: s3
  access_key_id: AKIAI3I2KMZFYPOKVKYA
  secret_access_key:
    secure: YjGgLn6bjFhjBFPCSmjsiOgQbeG90HdXgi2p/o70k0e6M7CqPX0iiE0w8ZYie9rUxTRWtqYY7RJU4KU1Q4HsIMOqc6hJwsmzGqwQxi5MI2jprGWESdZMcpzJdeAiFlo5QwhBFjP7/mD6CyEPEooa8y8hapgP7W313GVuRSVCd9SDTW52HAhbkIqlzzvNy8fb5pF2R45cllbZzi5ncB5cluh7DIlYQkRk8qbXQTGEt+q40UnRZxq3maPN2AIwjbC21rJkE+P+sN5FXzSPHNjR9tq7/AMYNqrzbcxdEs3y34G8RehbBv6SwQSkaDmaEhmceVt/Zv7JEwtD9GX6vR6hdBaW5Gax7qat6nTVSYgUGntWunSoh0FnRQDOFMnKYGF4JXAV2u0iYqi5q64qJ8rUFYjzAigNvvgOCONnARctxM3oPWUAkUczAqM8kBojziLuzQbVMm7STLztU+eWKTJ178mw04wY9sD60Gy5R5I00jgwTeX3pQ2UILI6zcUjpniwksaTFkeOTiNrQnVoIbG9uE2X1foRp91CXPPLn9FAbJwVQx+92GCN/lkjlrqF2gMzt8V8tYwqrbcba+KQXw22dBuSLonF+CmiILJYUCKzkuZ90t9vYyIChDG9iGlhLu/U6yCYYrL+oPI6Dh/8mUVCMbjko9+DkKJIpUg4OtpDGj8=
  bucket: bugattack.mcbanderson.com
  acl: public_read
  skip_cleanup: true
  local_dir: dist
  region: us-east-1
